package com.jiacer.modules.mybatis.model;

import java.math.BigDecimal;
import java.util.Date;

public class CourseInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course_info.course_id
     *
     * @mbggenerated Wed May 24 11:47:36 CST 2017
     */
    private Integer courseId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course_info.course_name
     *
     * @mbggenerated Wed May 24 11:47:36 CST 2017
     */
    private String courseName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course_info.course_type
     *
     * @mbggenerated Wed May 24 11:47:36 CST 2017
     */
    private String courseType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course_info.price
     *
     * @mbggenerated Wed May 24 11:47:36 CST 2017
     */
    private BigDecimal price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course_info.fit_service
     *
     * @mbggenerated Wed May 24 11:47:36 CST 2017
     */
    private String fitService;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course_info.sort_no
     *
     * @mbggenerated Wed May 24 11:47:36 CST 2017
     */
    private Integer sortNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course_info.summary
     *
     * @mbggenerated Wed May 24 11:47:36 CST 2017
     */
    private String summary;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course_info.creat_time
     *
     * @mbggenerated Wed May 24 11:47:36 CST 2017
     */
    private Date creatTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course_info.re_sign
     *
     * @mbggenerated Wed May 24 11:47:36 CST 2017
     */
    private String reSign;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course_info.status
     *
     * @mbggenerated Wed May 24 11:47:36 CST 2017
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course_info.creat_time
     *
     * @mbggenerated Wed May 24 11:47:36 CST 2017
     */
    private String courseTime;
    
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course_info.add_time
     *
     * @mbggenerated Wed May 24 11:47:36 CST 2017
     */
    private Date addTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course_info.add_account
     *
     * @mbggenerated Wed May 24 11:47:36 CST 2017
     */
    private String addAccount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course_info.modify_time
     *
     * @mbggenerated Wed May 24 11:47:36 CST 2017
     */
    private Date modifyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course_info.modify_account
     *
     * @mbggenerated Wed May 24 11:47:36 CST 2017
     */
    private String modifyAccount;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course_info.course_id
     *
     * @return the value of course_info.course_id
     *
     * @mbggenerated Wed May 24 11:47:36 CST 2017
     */
    public Integer getCourseId() {
        return courseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course_info.course_id
     *
     * @param courseId the value for course_info.course_id
     *
     * @mbggenerated Wed May 24 11:47:36 CST 2017
     */
    public void setCourseId(Integer courseId) {
        this.courseId = courseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course_info.course_name
     *
     * @return the value of course_info.course_name
     *
     * @mbggenerated Wed May 24 11:47:36 CST 2017
     */
    public String getCourseName() {
        return courseName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course_info.course_name
     *
     * @param courseName the value for course_info.course_name
     *
     * @mbggenerated Wed May 24 11:47:36 CST 2017
     */
    public void setCourseName(String courseName) {
        this.courseName = courseName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course_info.course_type
     *
     * @return the value of course_info.course_type
     *
     * @mbggenerated Wed May 24 11:47:36 CST 2017
     */
    public String getCourseType() {
        return courseType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course_info.course_type
     *
     * @param courseType the value for course_info.course_type
     *
     * @mbggenerated Wed May 24 11:47:36 CST 2017
     */
    public void setCourseType(String courseType) {
        this.courseType = courseType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course_info.price
     *
     * @return the value of course_info.price
     *
     * @mbggenerated Wed May 24 11:47:36 CST 2017
     */
    public BigDecimal getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course_info.price
     *
     * @param price the value for course_info.price
     *
     * @mbggenerated Wed May 24 11:47:36 CST 2017
     */
    public void setPrice(BigDecimal price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course_info.fit_service
     *
     * @return the value of course_info.fit_service
     *
     * @mbggenerated Wed May 24 11:47:36 CST 2017
     */
    public String getFitService() {
        return fitService;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course_info.fit_service
     *
     * @param fitService the value for course_info.fit_service
     *
     * @mbggenerated Wed May 24 11:47:36 CST 2017
     */
    public void setFitService(String fitService) {
        this.fitService = fitService;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course_info.sort_no
     *
     * @return the value of course_info.sort_no
     *
     * @mbggenerated Wed May 24 11:47:36 CST 2017
     */
    public Integer getSortNo() {
        return sortNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course_info.sort_no
     *
     * @param sortNo the value for course_info.sort_no
     *
     * @mbggenerated Wed May 24 11:47:36 CST 2017
     */
    public void setSortNo(Integer sortNo) {
        this.sortNo = sortNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course_info.summary
     *
     * @return the value of course_info.summary
     *
     * @mbggenerated Wed May 24 11:47:36 CST 2017
     */
    public String getSummary() {
        return summary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course_info.summary
     *
     * @param summary the value for course_info.summary
     *
     * @mbggenerated Wed May 24 11:47:36 CST 2017
     */
    public void setSummary(String summary) {
        this.summary = summary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course_info.creat_time
     *
     * @return the value of course_info.creat_time
     *
     * @mbggenerated Wed May 24 11:47:36 CST 2017
     */
    public Date getCreatTime() {
        return creatTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course_info.creat_time
     *
     * @param creatTime the value for course_info.creat_time
     *
     * @mbggenerated Wed May 24 11:47:36 CST 2017
     */
    public void setCreatTime(Date creatTime) {
        this.creatTime = creatTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course_info.re_sign
     *
     * @return the value of course_info.re_sign
     *
     * @mbggenerated Wed May 24 11:47:36 CST 2017
     */
    public String getReSign() {
        return reSign;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course_info.re_sign
     *
     * @param reSign the value for course_info.re_sign
     *
     * @mbggenerated Wed May 24 11:47:36 CST 2017
     */
    public void setReSign(String reSign) {
        this.reSign = reSign;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course_info.status
     *
     * @return the value of course_info.status
     *
     * @mbggenerated Wed May 24 11:47:36 CST 2017
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course_info.status
     *
     * @param status the value for course_info.status
     *
     * @mbggenerated Wed May 24 11:47:36 CST 2017
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course_info.add_time
     *
     * @return the value of course_info.add_time
     *
     * @mbggenerated Wed May 24 11:47:36 CST 2017
     */
    public Date getAddTime() {
        return addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course_info.add_time
     *
     * @param addTime the value for course_info.add_time
     *
     * @mbggenerated Wed May 24 11:47:36 CST 2017
     */
    public void setAddTime(Date addTime) {
        this.addTime = addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course_info.add_account
     *
     * @return the value of course_info.add_account
     *
     * @mbggenerated Wed May 24 11:47:36 CST 2017
     */
    public String getAddAccount() {
        return addAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course_info.add_account
     *
     * @param addAccount the value for course_info.add_account
     *
     * @mbggenerated Wed May 24 11:47:36 CST 2017
     */
    public void setAddAccount(String addAccount) {
        this.addAccount = addAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course_info.modify_time
     *
     * @return the value of course_info.modify_time
     *
     * @mbggenerated Wed May 24 11:47:36 CST 2017
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course_info.modify_time
     *
     * @param modifyTime the value for course_info.modify_time
     *
     * @mbggenerated Wed May 24 11:47:36 CST 2017
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course_info.modify_account
     *
     * @return the value of course_info.modify_account
     *
     * @mbggenerated Wed May 24 11:47:36 CST 2017
     */
    public String getModifyAccount() {
        return modifyAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course_info.modify_account
     *
     * @param modifyAccount the value for course_info.modify_account
     *
     * @mbggenerated Wed May 24 11:47:36 CST 2017
     */
    public void setModifyAccount(String modifyAccount) {
        this.modifyAccount = modifyAccount;
    }

	public String getCourseTime() {
		return courseTime;
	}

	public void setCourseTime(String courseTime) {
		this.courseTime = courseTime;
	}

	
}