package com.jiacer.modules.mybatis.model;

import java.math.BigDecimal;
import java.util.Date;

public class Orders {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.ORDER_NO
     *
     * @mbggenerated Wed May 31 13:02:39 CST 2017
     */
    private String orderNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.USER_ID
     *
     * @mbggenerated Wed May 31 13:02:39 CST 2017
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.INVITER_ID
     *
     * @mbggenerated Wed May 31 13:02:39 CST 2017
     */
    private Integer inviterId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.COURSE_ID
     *
     * @mbggenerated Wed May 31 13:02:39 CST 2017
     */
    private Integer courseId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.ORDER_TIME
     *
     * @mbggenerated Wed May 31 13:02:39 CST 2017
     */
    private Date orderTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.ORDER_STATUS
     *
     * @mbggenerated Wed May 31 13:02:39 CST 2017
     */
    private String orderStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.PAY_TYPE
     *
     * @mbggenerated Wed May 31 13:02:39 CST 2017
     */
    private String payType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.AMOUNT
     *
     * @mbggenerated Wed May 31 13:02:39 CST 2017
     */
    private BigDecimal amount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.TRADE_CHANNEL
     *
     * @mbggenerated Wed May 31 13:02:39 CST 2017
     */
    private String tradeChannel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.IS_INVITED
     *
     * @mbggenerated Wed May 31 13:02:39 CST 2017
     */
    private String isInvited;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.add_time
     *
     * @mbggenerated Wed May 31 13:02:39 CST 2017
     */
    private Date addTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.add_account
     *
     * @mbggenerated Wed May 31 13:02:39 CST 2017
     */
    private String addAccount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.modify_time
     *
     * @mbggenerated Wed May 31 13:02:39 CST 2017
     */
    private Date modifyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.modify_account
     *
     * @mbggenerated Wed May 31 13:02:39 CST 2017
     */
    private String modifyAccount;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.ORDER_NO
     *
     * @return the value of orders.ORDER_NO
     *
     * @mbggenerated Wed May 31 13:02:39 CST 2017
     */
    public String getOrderNo() {
        return orderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.ORDER_NO
     *
     * @param orderNo the value for orders.ORDER_NO
     *
     * @mbggenerated Wed May 31 13:02:39 CST 2017
     */
    public void setOrderNo(String orderNo) {
        this.orderNo = orderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.USER_ID
     *
     * @return the value of orders.USER_ID
     *
     * @mbggenerated Wed May 31 13:02:39 CST 2017
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.USER_ID
     *
     * @param userId the value for orders.USER_ID
     *
     * @mbggenerated Wed May 31 13:02:39 CST 2017
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.INVITER_ID
     *
     * @return the value of orders.INVITER_ID
     *
     * @mbggenerated Wed May 31 13:02:39 CST 2017
     */
    public Integer getInviterId() {
        return inviterId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.INVITER_ID
     *
     * @param inviterId the value for orders.INVITER_ID
     *
     * @mbggenerated Wed May 31 13:02:39 CST 2017
     */
    public void setInviterId(Integer inviterId) {
        this.inviterId = inviterId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.COURSE_ID
     *
     * @return the value of orders.COURSE_ID
     *
     * @mbggenerated Wed May 31 13:02:39 CST 2017
     */
    public Integer getCourseId() {
        return courseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.COURSE_ID
     *
     * @param courseId the value for orders.COURSE_ID
     *
     * @mbggenerated Wed May 31 13:02:39 CST 2017
     */
    public void setCourseId(Integer courseId) {
        this.courseId = courseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.ORDER_TIME
     *
     * @return the value of orders.ORDER_TIME
     *
     * @mbggenerated Wed May 31 13:02:39 CST 2017
     */
    public Date getOrderTime() {
        return orderTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.ORDER_TIME
     *
     * @param orderTime the value for orders.ORDER_TIME
     *
     * @mbggenerated Wed May 31 13:02:39 CST 2017
     */
    public void setOrderTime(Date orderTime) {
        this.orderTime = orderTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.ORDER_STATUS
     *
     * @return the value of orders.ORDER_STATUS
     *
     * @mbggenerated Wed May 31 13:02:39 CST 2017
     */
    public String getOrderStatus() {
        return orderStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.ORDER_STATUS
     *
     * @param orderStatus the value for orders.ORDER_STATUS
     *
     * @mbggenerated Wed May 31 13:02:39 CST 2017
     */
    public void setOrderStatus(String orderStatus) {
        this.orderStatus = orderStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.PAY_TYPE
     *
     * @return the value of orders.PAY_TYPE
     *
     * @mbggenerated Wed May 31 13:02:39 CST 2017
     */
    public String getPayType() {
        return payType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.PAY_TYPE
     *
     * @param payType the value for orders.PAY_TYPE
     *
     * @mbggenerated Wed May 31 13:02:39 CST 2017
     */
    public void setPayType(String payType) {
        this.payType = payType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.AMOUNT
     *
     * @return the value of orders.AMOUNT
     *
     * @mbggenerated Wed May 31 13:02:39 CST 2017
     */
    public BigDecimal getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.AMOUNT
     *
     * @param amount the value for orders.AMOUNT
     *
     * @mbggenerated Wed May 31 13:02:39 CST 2017
     */
    public void setAmount(BigDecimal amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.TRADE_CHANNEL
     *
     * @return the value of orders.TRADE_CHANNEL
     *
     * @mbggenerated Wed May 31 13:02:39 CST 2017
     */
    public String getTradeChannel() {
        return tradeChannel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.TRADE_CHANNEL
     *
     * @param tradeChannel the value for orders.TRADE_CHANNEL
     *
     * @mbggenerated Wed May 31 13:02:39 CST 2017
     */
    public void setTradeChannel(String tradeChannel) {
        this.tradeChannel = tradeChannel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.IS_INVITED
     *
     * @return the value of orders.IS_INVITED
     *
     * @mbggenerated Wed May 31 13:02:39 CST 2017
     */
    public String getIsInvited() {
        return isInvited;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.IS_INVITED
     *
     * @param isInvited the value for orders.IS_INVITED
     *
     * @mbggenerated Wed May 31 13:02:39 CST 2017
     */
    public void setIsInvited(String isInvited) {
        this.isInvited = isInvited;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.add_time
     *
     * @return the value of orders.add_time
     *
     * @mbggenerated Wed May 31 13:02:39 CST 2017
     */
    public Date getAddTime() {
        return addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.add_time
     *
     * @param addTime the value for orders.add_time
     *
     * @mbggenerated Wed May 31 13:02:39 CST 2017
     */
    public void setAddTime(Date addTime) {
        this.addTime = addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.add_account
     *
     * @return the value of orders.add_account
     *
     * @mbggenerated Wed May 31 13:02:39 CST 2017
     */
    public String getAddAccount() {
        return addAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.add_account
     *
     * @param addAccount the value for orders.add_account
     *
     * @mbggenerated Wed May 31 13:02:39 CST 2017
     */
    public void setAddAccount(String addAccount) {
        this.addAccount = addAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.modify_time
     *
     * @return the value of orders.modify_time
     *
     * @mbggenerated Wed May 31 13:02:39 CST 2017
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.modify_time
     *
     * @param modifyTime the value for orders.modify_time
     *
     * @mbggenerated Wed May 31 13:02:39 CST 2017
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.modify_account
     *
     * @return the value of orders.modify_account
     *
     * @mbggenerated Wed May 31 13:02:39 CST 2017
     */
    public String getModifyAccount() {
        return modifyAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.modify_account
     *
     * @param modifyAccount the value for orders.modify_account
     *
     * @mbggenerated Wed May 31 13:02:39 CST 2017
     */
    public void setModifyAccount(String modifyAccount) {
        this.modifyAccount = modifyAccount;
    }
}