package com.jiacer.modules.mybatis.model;

import java.math.BigDecimal;
import java.util.Date;

public class RedPacket {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column red_packet.ID
     *
     * @mbggenerated Fri Jun 02 16:06:04 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column red_packet.ORDER_NO
     *
     * @mbggenerated Fri Jun 02 16:06:04 CST 2017
     */
    private String orderNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column red_packet.USER_ID
     *
     * @mbggenerated Fri Jun 02 16:06:04 CST 2017
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column red_packet.USER_NAME
     *
     * @mbggenerated Fri Jun 02 16:06:04 CST 2017
     */
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column red_packet.INVITER_ID
     *
     * @mbggenerated Fri Jun 02 16:06:04 CST 2017
     */
    private Integer inviterId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column red_packet.INVITER_NAME
     *
     * @mbggenerated Fri Jun 02 16:06:04 CST 2017
     */
    private String inviterName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column red_packet.INVITER_OPENID
     *
     * @mbggenerated Fri Jun 02 16:06:04 CST 2017
     */
    private String inviterOpenid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column red_packet.INVITER_MOBILE
     *
     * @mbggenerated Fri Jun 02 16:06:04 CST 2017
     */
    private String inviterMobile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column red_packet.STATUS
     *
     * @mbggenerated Fri Jun 02 16:06:04 CST 2017
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column red_packet.AMOUNT
     *
     * @mbggenerated Fri Jun 02 16:06:04 CST 2017
     */
    private BigDecimal amount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column red_packet.SEND_TIME
     *
     * @mbggenerated Fri Jun 02 16:06:04 CST 2017
     */
    private Date sendTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column red_packet.is_usable
     *
     * @mbggenerated Fri Jun 02 16:06:04 CST 2017
     */
    private String isUsable;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column red_packet.add_time
     *
     * @mbggenerated Fri Jun 02 16:06:04 CST 2017
     */
    private Date addTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column red_packet.add_account
     *
     * @mbggenerated Fri Jun 02 16:06:04 CST 2017
     */
    private String addAccount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column red_packet.modify_time
     *
     * @mbggenerated Fri Jun 02 16:06:04 CST 2017
     */
    private Date modifyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column red_packet.modify_account
     *
     * @mbggenerated Fri Jun 02 16:06:04 CST 2017
     */
    private String modifyAccount;

    private String redpackWxNo;

    public String getRedpackWxNo() {
        return redpackWxNo;
    }

    public void setRedpackWxNo(String redpackWxNo) {
        this.redpackWxNo = redpackWxNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column red_packet.ID
     *
     * @return the value of red_packet.ID
     *
     * @mbggenerated Fri Jun 02 16:06:04 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column red_packet.ID
     *
     * @param id the value for red_packet.ID
     *
     * @mbggenerated Fri Jun 02 16:06:04 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column red_packet.ORDER_NO
     *
     * @return the value of red_packet.ORDER_NO
     *
     * @mbggenerated Fri Jun 02 16:06:04 CST 2017
     */
    public String getOrderNo() {
        return orderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column red_packet.ORDER_NO
     *
     * @param orderNo the value for red_packet.ORDER_NO
     *
     * @mbggenerated Fri Jun 02 16:06:04 CST 2017
     */
    public void setOrderNo(String orderNo) {
        this.orderNo = orderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column red_packet.USER_ID
     *
     * @return the value of red_packet.USER_ID
     *
     * @mbggenerated Fri Jun 02 16:06:04 CST 2017
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column red_packet.USER_ID
     *
     * @param userId the value for red_packet.USER_ID
     *
     * @mbggenerated Fri Jun 02 16:06:04 CST 2017
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column red_packet.USER_NAME
     *
     * @return the value of red_packet.USER_NAME
     *
     * @mbggenerated Fri Jun 02 16:06:04 CST 2017
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column red_packet.USER_NAME
     *
     * @param userName the value for red_packet.USER_NAME
     *
     * @mbggenerated Fri Jun 02 16:06:04 CST 2017
     */
    public void setUserName(String userName) {
        this.userName = userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column red_packet.INVITER_ID
     *
     * @return the value of red_packet.INVITER_ID
     *
     * @mbggenerated Fri Jun 02 16:06:04 CST 2017
     */
    public Integer getInviterId() {
        return inviterId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column red_packet.INVITER_ID
     *
     * @param inviterId the value for red_packet.INVITER_ID
     *
     * @mbggenerated Fri Jun 02 16:06:04 CST 2017
     */
    public void setInviterId(Integer inviterId) {
        this.inviterId = inviterId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column red_packet.INVITER_NAME
     *
     * @return the value of red_packet.INVITER_NAME
     *
     * @mbggenerated Fri Jun 02 16:06:04 CST 2017
     */
    public String getInviterName() {
        return inviterName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column red_packet.INVITER_NAME
     *
     * @param inviterName the value for red_packet.INVITER_NAME
     *
     * @mbggenerated Fri Jun 02 16:06:04 CST 2017
     */
    public void setInviterName(String inviterName) {
        this.inviterName = inviterName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column red_packet.INVITER_OPENID
     *
     * @return the value of red_packet.INVITER_OPENID
     *
     * @mbggenerated Fri Jun 02 16:06:04 CST 2017
     */
    public String getInviterOpenid() {
        return inviterOpenid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column red_packet.INVITER_OPENID
     *
     * @param inviterOpenid the value for red_packet.INVITER_OPENID
     *
     * @mbggenerated Fri Jun 02 16:06:04 CST 2017
     */
    public void setInviterOpenid(String inviterOpenid) {
        this.inviterOpenid = inviterOpenid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column red_packet.INVITER_MOBILE
     *
     * @return the value of red_packet.INVITER_MOBILE
     *
     * @mbggenerated Fri Jun 02 16:06:04 CST 2017
     */
    public String getInviterMobile() {
        return inviterMobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column red_packet.INVITER_MOBILE
     *
     * @param inviterMobile the value for red_packet.INVITER_MOBILE
     *
     * @mbggenerated Fri Jun 02 16:06:04 CST 2017
     */
    public void setInviterMobile(String inviterMobile) {
        this.inviterMobile = inviterMobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column red_packet.STATUS
     *
     * @return the value of red_packet.STATUS
     *
     * @mbggenerated Fri Jun 02 16:06:04 CST 2017
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column red_packet.STATUS
     *
     * @param status the value for red_packet.STATUS
     *
     * @mbggenerated Fri Jun 02 16:06:04 CST 2017
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column red_packet.AMOUNT
     *
     * @return the value of red_packet.AMOUNT
     *
     * @mbggenerated Fri Jun 02 16:06:04 CST 2017
     */
    public BigDecimal getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column red_packet.AMOUNT
     *
     * @param amount the value for red_packet.AMOUNT
     *
     * @mbggenerated Fri Jun 02 16:06:04 CST 2017
     */
    public void setAmount(BigDecimal amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column red_packet.SEND_TIME
     *
     * @return the value of red_packet.SEND_TIME
     *
     * @mbggenerated Fri Jun 02 16:06:04 CST 2017
     */
    public Date getSendTime() {
        return sendTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column red_packet.SEND_TIME
     *
     * @param sendTime the value for red_packet.SEND_TIME
     *
     * @mbggenerated Fri Jun 02 16:06:04 CST 2017
     */
    public void setSendTime(Date sendTime) {
        this.sendTime = sendTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column red_packet.is_usable
     *
     * @return the value of red_packet.is_usable
     *
     * @mbggenerated Fri Jun 02 16:06:04 CST 2017
     */
    public String getIsUsable() {
        return isUsable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column red_packet.is_usable
     *
     * @param isUsable the value for red_packet.is_usable
     *
     * @mbggenerated Fri Jun 02 16:06:04 CST 2017
     */
    public void setIsUsable(String isUsable) {
        this.isUsable = isUsable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column red_packet.add_time
     *
     * @return the value of red_packet.add_time
     *
     * @mbggenerated Fri Jun 02 16:06:04 CST 2017
     */
    public Date getAddTime() {
        return addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column red_packet.add_time
     *
     * @param addTime the value for red_packet.add_time
     *
     * @mbggenerated Fri Jun 02 16:06:04 CST 2017
     */
    public void setAddTime(Date addTime) {
        this.addTime = addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column red_packet.add_account
     *
     * @return the value of red_packet.add_account
     *
     * @mbggenerated Fri Jun 02 16:06:04 CST 2017
     */
    public String getAddAccount() {
        return addAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column red_packet.add_account
     *
     * @param addAccount the value for red_packet.add_account
     *
     * @mbggenerated Fri Jun 02 16:06:04 CST 2017
     */
    public void setAddAccount(String addAccount) {
        this.addAccount = addAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column red_packet.modify_time
     *
     * @return the value of red_packet.modify_time
     *
     * @mbggenerated Fri Jun 02 16:06:04 CST 2017
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column red_packet.modify_time
     *
     * @param modifyTime the value for red_packet.modify_time
     *
     * @mbggenerated Fri Jun 02 16:06:04 CST 2017
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column red_packet.modify_account
     *
     * @return the value of red_packet.modify_account
     *
     * @mbggenerated Fri Jun 02 16:06:04 CST 2017
     */
    public String getModifyAccount() {
        return modifyAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column red_packet.modify_account
     *
     * @param modifyAccount the value for red_packet.modify_account
     *
     * @mbggenerated Fri Jun 02 16:06:04 CST 2017
     */
    public void setModifyAccount(String modifyAccount) {
        this.modifyAccount = modifyAccount;
    }
    
    private String pay_status; //红包状态
    
    private String failCode; //失败code
    
    private String failReason; //失败原因
    
    private String redpackNo; //红包编号
    
    

	public String getPay_status() {
		return pay_status;
	}

	public void setPay_status(String pay_status) {
		this.pay_status = pay_status;
	}

	

	public String getFailCode() {
		return failCode;
	}

	public void setFailCode(String failCode) {
		this.failCode = failCode;
	}

	public String getFailReason() {
		return failReason;
	}

	public void setFailReason(String failReason) {
		this.failReason = failReason;
	}

	public String getRedpackNo() {
		return redpackNo;
	}

	public void setRedpackNo(String redpackNo) {
		this.redpackNo = redpackNo;
	}
    
    
}