package com.jiacer.modules.mybatis.model;

import java.util.Date;

import com.jiacer.modules.common.persistence.ModelSerializable;

public class Schools implements ModelSerializable{
   
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column schools.id
	 * @mbggenerated  Thu Jun 22 11:46:27 CST 2017
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column schools.school_name
	 * @mbggenerated  Thu Jun 22 11:46:27 CST 2017
	 */
	private String schoolName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column schools.privince
	 * @mbggenerated  Thu Jun 22 11:46:27 CST 2017
	 */
	private String privince;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column schools.city
	 * @mbggenerated  Thu Jun 22 11:46:27 CST 2017
	 */
	private String city;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column schools.area
	 * @mbggenerated  Thu Jun 22 11:46:27 CST 2017
	 */
	private String area;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column schools.school_address
	 * @mbggenerated  Thu Jun 22 11:46:27 CST 2017
	 */
	private String schoolAddress;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column schools.school_phone
	 * @mbggenerated  Thu Jun 22 11:46:27 CST 2017
	 */
	private String schoolPhone;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column schools.contacts
	 * @mbggenerated  Thu Jun 22 11:46:27 CST 2017
	 */
	private String contacts;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column schools.contact_phone
	 * @mbggenerated  Thu Jun 22 11:46:27 CST 2017
	 */
	private String contactPhone;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column schools.company_name
	 * @mbggenerated  Thu Jun 22 11:46:27 CST 2017
	 */
	private String companyName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column schools.licence_no
	 * @mbggenerated  Thu Jun 22 11:46:27 CST 2017
	 */
	private String licenceNo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column schools.licence_img
	 * @mbggenerated  Thu Jun 22 11:46:27 CST 2017
	 */
	private String licenceImg;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column schools.agent_name
	 * @mbggenerated  Thu Jun 22 11:46:27 CST 2017
	 */
	private String agentName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column schools.agent_id_number
	 * @mbggenerated  Thu Jun 22 11:46:27 CST 2017
	 */
	private String agentIdNumber;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column schools.idcard_Front_img
	 * @mbggenerated  Thu Jun 22 11:46:27 CST 2017
	 */
	private String idcardFrontImg;
	
	private String idcardBackImg;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column schools.saler
	 * @mbggenerated  Thu Jun 22 11:46:27 CST 2017
	 */
	private String saler;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column schools.applt_time
	 * @mbggenerated  Thu Jun 22 11:46:27 CST 2017
	 */
	private Date appltTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column schools.remarks
	 * @mbggenerated  Thu Jun 22 11:46:27 CST 2017
	 */
	private String remarks;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column schools.apply_courses
	 * @mbggenerated  Thu Jun 22 11:46:27 CST 2017
	 */
	private String applyCourses;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column schools.is_usable
	 * @mbggenerated  Thu Jun 22 11:46:27 CST 2017
	 */
	private String isUsable;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column schools.add_time
	 * @mbggenerated  Thu Jun 22 11:46:27 CST 2017
	 */
	private Date addTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column schools.add_account
	 * @mbggenerated  Thu Jun 22 11:46:28 CST 2017
	 */
	private String addAccount;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column schools.modify_time
	 * @mbggenerated  Thu Jun 22 11:46:28 CST 2017
	 */
	private Date modifyTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column schools.modify_account
	 * @mbggenerated  Thu Jun 22 11:46:28 CST 2017
	 */
	private String modifyAccount;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column schools.id
	 * @return  the value of schools.id
	 * @mbggenerated  Thu Jun 22 11:46:27 CST 2017
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column schools.id
	 * @param id  the value for schools.id
	 * @mbggenerated  Thu Jun 22 11:46:27 CST 2017
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column schools.school_name
	 * @return  the value of schools.school_name
	 * @mbggenerated  Thu Jun 22 11:46:27 CST 2017
	 */
	public String getSchoolName() {
		return schoolName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column schools.school_name
	 * @param schoolName  the value for schools.school_name
	 * @mbggenerated  Thu Jun 22 11:46:27 CST 2017
	 */
	public void setSchoolName(String schoolName) {
		this.schoolName = schoolName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column schools.privince
	 * @return  the value of schools.privince
	 * @mbggenerated  Thu Jun 22 11:46:27 CST 2017
	 */
	public String getPrivince() {
		return privince;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column schools.privince
	 * @param privince  the value for schools.privince
	 * @mbggenerated  Thu Jun 22 11:46:27 CST 2017
	 */
	public void setPrivince(String privince) {
		this.privince = privince;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column schools.city
	 * @return  the value of schools.city
	 * @mbggenerated  Thu Jun 22 11:46:27 CST 2017
	 */
	public String getCity() {
		return city;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column schools.city
	 * @param city  the value for schools.city
	 * @mbggenerated  Thu Jun 22 11:46:27 CST 2017
	 */
	public void setCity(String city) {
		this.city = city;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column schools.area
	 * @return  the value of schools.area
	 * @mbggenerated  Thu Jun 22 11:46:27 CST 2017
	 */
	public String getArea() {
		return area;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column schools.area
	 * @param area  the value for schools.area
	 * @mbggenerated  Thu Jun 22 11:46:27 CST 2017
	 */
	public void setArea(String area) {
		this.area = area;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column schools.school_address
	 * @return  the value of schools.school_address
	 * @mbggenerated  Thu Jun 22 11:46:27 CST 2017
	 */
	public String getSchoolAddress() {
		return schoolAddress;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column schools.school_address
	 * @param schoolAddress  the value for schools.school_address
	 * @mbggenerated  Thu Jun 22 11:46:27 CST 2017
	 */
	public void setSchoolAddress(String schoolAddress) {
		this.schoolAddress = schoolAddress;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column schools.school_phone
	 * @return  the value of schools.school_phone
	 * @mbggenerated  Thu Jun 22 11:46:27 CST 2017
	 */
	public String getSchoolPhone() {
		return schoolPhone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column schools.school_phone
	 * @param schoolPhone  the value for schools.school_phone
	 * @mbggenerated  Thu Jun 22 11:46:27 CST 2017
	 */
	public void setSchoolPhone(String schoolPhone) {
		this.schoolPhone = schoolPhone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column schools.contacts
	 * @return  the value of schools.contacts
	 * @mbggenerated  Thu Jun 22 11:46:27 CST 2017
	 */
	public String getContacts() {
		return contacts;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column schools.contacts
	 * @param contacts  the value for schools.contacts
	 * @mbggenerated  Thu Jun 22 11:46:27 CST 2017
	 */
	public void setContacts(String contacts) {
		this.contacts = contacts;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column schools.contact_phone
	 * @return  the value of schools.contact_phone
	 * @mbggenerated  Thu Jun 22 11:46:27 CST 2017
	 */
	public String getContactPhone() {
		return contactPhone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column schools.contact_phone
	 * @param contactPhone  the value for schools.contact_phone
	 * @mbggenerated  Thu Jun 22 11:46:27 CST 2017
	 */
	public void setContactPhone(String contactPhone) {
		this.contactPhone = contactPhone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column schools.company_name
	 * @return  the value of schools.company_name
	 * @mbggenerated  Thu Jun 22 11:46:27 CST 2017
	 */
	public String getCompanyName() {
		return companyName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column schools.company_name
	 * @param companyName  the value for schools.company_name
	 * @mbggenerated  Thu Jun 22 11:46:27 CST 2017
	 */
	public void setCompanyName(String companyName) {
		this.companyName = companyName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column schools.licence_no
	 * @return  the value of schools.licence_no
	 * @mbggenerated  Thu Jun 22 11:46:27 CST 2017
	 */
	
	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column schools.licence_img
	 * @return  the value of schools.licence_img
	 * @mbggenerated  Thu Jun 22 11:46:27 CST 2017
	 */
	public String getLicenceImg() {
		return licenceImg;
	}

	public String getLicenceNo() {
		return licenceNo;
	}

	public void setLicenceNo(String licenceNo) {
		this.licenceNo = licenceNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column schools.licence_img
	 * @param licenceImg  the value for schools.licence_img
	 * @mbggenerated  Thu Jun 22 11:46:27 CST 2017
	 */
	public void setLicenceImg(String licenceImg) {
		this.licenceImg = licenceImg;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column schools.agent_name
	 * @return  the value of schools.agent_name
	 * @mbggenerated  Thu Jun 22 11:46:27 CST 2017
	 */
	public String getAgentName() {
		return agentName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column schools.agent_name
	 * @param agentName  the value for schools.agent_name
	 * @mbggenerated  Thu Jun 22 11:46:27 CST 2017
	 */
	public void setAgentName(String agentName) {
		this.agentName = agentName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column schools.agent_id_number
	 * @return  the value of schools.agent_id_number
	 * @mbggenerated  Thu Jun 22 11:46:27 CST 2017
	 */
	
	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column schools.idcard_Front_img
	 * @return  the value of schools.idcard_Front_img
	 * @mbggenerated  Thu Jun 22 11:46:27 CST 2017
	 */
	public String getIdcardFrontImg() {
		return idcardFrontImg;
	}

	public String getAgentIdNumber() {
		return agentIdNumber;
	}

	public void setAgentIdNumber(String agentIdNumber) {
		this.agentIdNumber = agentIdNumber;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column schools.idcard_Front_img
	 * @param idcardFrontImg  the value for schools.idcard_Front_img
	 * @mbggenerated  Thu Jun 22 11:46:27 CST 2017
	 */
	public void setIdcardFrontImg(String idcardFrontImg) {
		this.idcardFrontImg = idcardFrontImg;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column schools.saler
	 * @return  the value of schools.saler
	 * @mbggenerated  Thu Jun 22 11:46:27 CST 2017
	 */
	public String getSaler() {
		return saler;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column schools.saler
	 * @param saler  the value for schools.saler
	 * @mbggenerated  Thu Jun 22 11:46:27 CST 2017
	 */
	public void setSaler(String saler) {
		this.saler = saler;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column schools.applt_time
	 * @return  the value of schools.applt_time
	 * @mbggenerated  Thu Jun 22 11:46:27 CST 2017
	 */
	public Date getAppltTime() {
		return appltTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column schools.applt_time
	 * @param appltTime  the value for schools.applt_time
	 * @mbggenerated  Thu Jun 22 11:46:27 CST 2017
	 */
	public void setAppltTime(Date appltTime) {
		this.appltTime = appltTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column schools.remarks
	 * @return  the value of schools.remarks
	 * @mbggenerated  Thu Jun 22 11:46:27 CST 2017
	 */
	public String getRemarks() {
		return remarks;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column schools.remarks
	 * @param remarks  the value for schools.remarks
	 * @mbggenerated  Thu Jun 22 11:46:27 CST 2017
	 */
	public void setRemarks(String remarks) {
		this.remarks = remarks;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column schools.apply_courses
	 * @return  the value of schools.apply_courses
	 * @mbggenerated  Thu Jun 22 11:46:27 CST 2017
	 */
	public String getApplyCourses() {
		return applyCourses;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column schools.apply_courses
	 * @param applyCourses  the value for schools.apply_courses
	 * @mbggenerated  Thu Jun 22 11:46:27 CST 2017
	 */
	public void setApplyCourses(String applyCourses) {
		this.applyCourses = applyCourses;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column schools.is_usable
	 * @return  the value of schools.is_usable
	 * @mbggenerated  Thu Jun 22 11:46:27 CST 2017
	 */
	public String getIsUsable() {
		return isUsable;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column schools.is_usable
	 * @param isUsable  the value for schools.is_usable
	 * @mbggenerated  Thu Jun 22 11:46:27 CST 2017
	 */
	public void setIsUsable(String isUsable) {
		this.isUsable = isUsable;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column schools.add_time
	 * @return  the value of schools.add_time
	 * @mbggenerated  Thu Jun 22 11:46:27 CST 2017
	 */
	public Date getAddTime() {
		return addTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column schools.add_time
	 * @param addTime  the value for schools.add_time
	 * @mbggenerated  Thu Jun 22 11:46:28 CST 2017
	 */
	public void setAddTime(Date addTime) {
		this.addTime = addTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column schools.add_account
	 * @return  the value of schools.add_account
	 * @mbggenerated  Thu Jun 22 11:46:28 CST 2017
	 */
	public String getAddAccount() {
		return addAccount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column schools.add_account
	 * @param addAccount  the value for schools.add_account
	 * @mbggenerated  Thu Jun 22 11:46:28 CST 2017
	 */
	public void setAddAccount(String addAccount) {
		this.addAccount = addAccount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column schools.modify_time
	 * @return  the value of schools.modify_time
	 * @mbggenerated  Thu Jun 22 11:46:28 CST 2017
	 */
	public Date getModifyTime() {
		return modifyTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column schools.modify_time
	 * @param modifyTime  the value for schools.modify_time
	 * @mbggenerated  Thu Jun 22 11:46:28 CST 2017
	 */
	public void setModifyTime(Date modifyTime) {
		this.modifyTime = modifyTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column schools.modify_account
	 * @return  the value of schools.modify_account
	 * @mbggenerated  Thu Jun 22 11:46:28 CST 2017
	 */
	public String getModifyAccount() {
		return modifyAccount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column schools.modify_account
	 * @param modifyAccount  the value for schools.modify_account
	 * @mbggenerated  Thu Jun 22 11:46:28 CST 2017
	 */
	public void setModifyAccount(String modifyAccount) {
		this.modifyAccount = modifyAccount;
	}

	public String getIdcardBackImg() {
		return idcardBackImg;
	}

	public void setIdcardBackImg(String idcardBackImg) {
		this.idcardBackImg = idcardBackImg;
	}

	private static final long serialVersionUID = 1L;

}