package com.jiacer.modules.mybatis.model;

import java.util.Date;

public class TemplateInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column template_info.template_id
     *
     * @mbggenerated Wed May 24 17:50:47 CST 2017
     */
    private Integer templateId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column template_info.course_id
     *
     * @mbggenerated Wed May 24 17:50:47 CST 2017
     */
    private Integer courseId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column template_info.subject_type
     *
     * @mbggenerated Wed May 24 17:50:47 CST 2017
     */
    private String subjectType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column template_info.subject_count
     *
     * @mbggenerated Wed May 24 17:50:47 CST 2017
     */
    private String subjectCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column template_info.subject_score
     *
     * @mbggenerated Wed May 24 17:50:47 CST 2017
     */
    private String subjectScore;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column template_info.is_usable
     *
     * @mbggenerated Wed May 24 17:50:47 CST 2017
     */
    private String isUsable;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column template_info.add_time
     *
     * @mbggenerated Wed May 24 17:50:47 CST 2017
     */
    private Date addTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column template_info.add_account
     *
     * @mbggenerated Wed May 24 17:50:47 CST 2017
     */
    private String addAccount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column template_info.modify_time
     *
     * @mbggenerated Wed May 24 17:50:47 CST 2017
     */
    private Date modifyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column template_info.modify_account
     *
     * @mbggenerated Wed May 24 17:50:47 CST 2017
     */
    private String modifyAccount;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column template_info.template_id
     *
     * @return the value of template_info.template_id
     *
     * @mbggenerated Wed May 24 17:50:47 CST 2017
     */
    public Integer getTemplateId() {
        return templateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column template_info.template_id
     *
     * @param templateId the value for template_info.template_id
     *
     * @mbggenerated Wed May 24 17:50:47 CST 2017
     */
    public void setTemplateId(Integer templateId) {
        this.templateId = templateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column template_info.course_id
     *
     * @return the value of template_info.course_id
     *
     * @mbggenerated Wed May 24 17:50:47 CST 2017
     */
    public Integer getCourseId() {
        return courseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column template_info.course_id
     *
     * @param courseId the value for template_info.course_id
     *
     * @mbggenerated Wed May 24 17:50:47 CST 2017
     */
    public void setCourseId(Integer courseId) {
        this.courseId = courseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column template_info.subject_type
     *
     * @return the value of template_info.subject_type
     *
     * @mbggenerated Wed May 24 17:50:47 CST 2017
     */
    public String getSubjectType() {
        return subjectType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column template_info.subject_type
     *
     * @param subjectType the value for template_info.subject_type
     *
     * @mbggenerated Wed May 24 17:50:47 CST 2017
     */
    public void setSubjectType(String subjectType) {
        this.subjectType = subjectType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column template_info.subject_count
     *
     * @return the value of template_info.subject_count
     *
     * @mbggenerated Wed May 24 17:50:47 CST 2017
     */
    public String getSubjectCount() {
        return subjectCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column template_info.subject_count
     *
     * @param subjectCount the value for template_info.subject_count
     *
     * @mbggenerated Wed May 24 17:50:47 CST 2017
     */
    public void setSubjectCount(String subjectCount) {
        this.subjectCount = subjectCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column template_info.subject_score
     *
     * @return the value of template_info.subject_score
     *
     * @mbggenerated Wed May 24 17:50:47 CST 2017
     */
    public String getSubjectScore() {
        return subjectScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column template_info.subject_score
     *
     * @param subjectScore the value for template_info.subject_score
     *
     * @mbggenerated Wed May 24 17:50:47 CST 2017
     */
    public void setSubjectScore(String subjectScore) {
        this.subjectScore = subjectScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column template_info.is_usable
     *
     * @return the value of template_info.is_usable
     *
     * @mbggenerated Wed May 24 17:50:47 CST 2017
     */
    public String getIsUsable() {
        return isUsable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column template_info.is_usable
     *
     * @param isUsable the value for template_info.is_usable
     *
     * @mbggenerated Wed May 24 17:50:47 CST 2017
     */
    public void setIsUsable(String isUsable) {
        this.isUsable = isUsable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column template_info.add_time
     *
     * @return the value of template_info.add_time
     *
     * @mbggenerated Wed May 24 17:50:47 CST 2017
     */
    public Date getAddTime() {
        return addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column template_info.add_time
     *
     * @param addTime the value for template_info.add_time
     *
     * @mbggenerated Wed May 24 17:50:47 CST 2017
     */
    public void setAddTime(Date addTime) {
        this.addTime = addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column template_info.add_account
     *
     * @return the value of template_info.add_account
     *
     * @mbggenerated Wed May 24 17:50:47 CST 2017
     */
    public String getAddAccount() {
        return addAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column template_info.add_account
     *
     * @param addAccount the value for template_info.add_account
     *
     * @mbggenerated Wed May 24 17:50:47 CST 2017
     */
    public void setAddAccount(String addAccount) {
        this.addAccount = addAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column template_info.modify_time
     *
     * @return the value of template_info.modify_time
     *
     * @mbggenerated Wed May 24 17:50:47 CST 2017
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column template_info.modify_time
     *
     * @param modifyTime the value for template_info.modify_time
     *
     * @mbggenerated Wed May 24 17:50:47 CST 2017
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column template_info.modify_account
     *
     * @return the value of template_info.modify_account
     *
     * @mbggenerated Wed May 24 17:50:47 CST 2017
     */
    public String getModifyAccount() {
        return modifyAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column template_info.modify_account
     *
     * @param modifyAccount the value for template_info.modify_account
     *
     * @mbggenerated Wed May 24 17:50:47 CST 2017
     */
    public void setModifyAccount(String modifyAccount) {
        this.modifyAccount = modifyAccount;
    }
}