package com.jiacer.modules.mybatis.dao;

import com.jiacer.modules.common.persistence.CrudDao;
import com.jiacer.modules.common.persistence.annotation.MyBatisDao;
import com.jiacer.modules.mybatis.entity.AuthorityEntity;
import com.jiacer.modules.mybatis.model.CertAuthority;
import com.jiacer.modules.mybatis.model.CertAuthorityExample;
import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;
@MyBatisDao
public interface CertAuthorityMapper extends CrudDao<AuthorityEntity> {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cert_authority
	 * @mbggenerated  Wed May 24 17:41:38 CST 2017
	 */
	int countByExample(CertAuthorityExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cert_authority
	 * @mbggenerated  Wed May 24 17:41:38 CST 2017
	 */
	int deleteByExample(CertAuthorityExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cert_authority
	 * @mbggenerated  Wed May 24 17:41:38 CST 2017
	 */
	int deleteByPrimaryKey(Integer authorityId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cert_authority
	 * @mbggenerated  Wed May 24 17:41:38 CST 2017
	 */
	int insert(CertAuthority record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cert_authority
	 * @mbggenerated  Wed May 24 17:41:38 CST 2017
	 */
	int insertSelective(AuthorityEntity record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cert_authority
	 * @mbggenerated  Wed May 24 17:41:38 CST 2017
	 */
	List<CertAuthority> selectByExample(CertAuthorityExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cert_authority
	 * @mbggenerated  Wed May 24 17:41:38 CST 2017
	 */
	CertAuthority selectByPrimaryKey(Integer authorityId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cert_authority
	 * @mbggenerated  Wed May 24 17:41:38 CST 2017
	 */
	int updateByExampleSelective(@Param("record") CertAuthority record, @Param("example") CertAuthorityExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cert_authority
	 * @mbggenerated  Wed May 24 17:41:38 CST 2017
	 */
	int updateByExample(@Param("record") CertAuthority record, @Param("example") CertAuthorityExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cert_authority
	 * @mbggenerated  Wed May 24 17:41:38 CST 2017
	 */
	int updateByPrimaryKeySelective(AuthorityEntity record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cert_authority
	 * @mbggenerated  Wed May 24 17:41:38 CST 2017
	 */
	int updateByPrimaryKey(CertAuthority record);
	
	
	
	/**
	 * 发证机构总数
	 * @param map
	 * @return
	 */
	Integer count(Map<Object, Object> map);

	/**
	 * 发证机构列表
	 * @param map
	 * @return
	 */
	List<AuthorityEntity> getPageList(Map<Object, Object> map);
	

	/**
	 * 
	 * @MethodName:getAllCertAuthority
	 * @Type:CertAuthorityMapper
	 * @Description:获取发证机构全部信息
	 * @Return:List<AuthorityEntity>
	 * @Param:@return
	 * @Thrown:
	 * @Date:Sep 27, 2017 5:38:54 PM
	 */
	List<AuthorityEntity> getAllCertAuthority();
	
}