package com.jiacer.modules.mybatis.dao;

import com.jiacer.modules.common.persistence.CrudDao;
import com.jiacer.modules.common.persistence.annotation.MyBatisDao;
import com.jiacer.modules.mybatis.entity.CourseInfoEntity;
import com.jiacer.modules.mybatis.entity.LearnTypesEntity;
import com.jiacer.modules.mybatis.model.CourseInfo;
import com.jiacer.modules.mybatis.model.CourseInfoExample;
import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;
@MyBatisDao
public interface CourseInfoMapper extends CrudDao<CourseInfoEntity>{
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_info
     *
     * @mbggenerated Wed May 24 11:47:36 CST 2017
     */
    int countByExample(CourseInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_info
     *
     * @mbggenerated Wed May 24 11:47:36 CST 2017
     */
    int deleteByExample(CourseInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_info
     *
     * @mbggenerated Wed May 24 11:47:36 CST 2017
     */
    int deleteByPrimaryKey(Integer courseId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_info
     *
     * @mbggenerated Wed May 24 11:47:36 CST 2017
     */
    int insert(CourseInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_info
     *
     * @mbggenerated Wed May 24 11:47:36 CST 2017
     */
    int insertSelective(CourseInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_info
     *
     * @mbggenerated Wed May 24 11:47:36 CST 2017
     */
    List<CourseInfo> selectByExample(CourseInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_info
     *
     * @mbggenerated Wed May 24 11:47:36 CST 2017
     */
    CourseInfo selectByPrimaryKey(Integer courseId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_info
     *
     * @mbggenerated Wed May 24 11:47:36 CST 2017
     */
    int updateByExampleSelective(@Param("record") CourseInfo record, @Param("example") CourseInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_info
     *
     * @mbggenerated Wed May 24 11:47:36 CST 2017
     */
    int updateByExample(@Param("record") CourseInfo record, @Param("example") CourseInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_info
     *
     * @mbggenerated Wed May 24 11:47:36 CST 2017
     */
    int updateByPrimaryKeySelective(CourseInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_info
     *
     * @mbggenerated Wed May 24 11:47:36 CST 2017
     */
    int updateByPrimaryKey(CourseInfo record);
    
    
    
    
    /**
	 * @param map
	 * @return
	 */
	Integer count(Map<Object, Object> map);

	/**
	 * @param map
	 * @return
	 */
	List<CourseInfoEntity> getPageList(Map<Object, Object> map);
	
	 CourseInfoEntity selectByCourseId(Integer courseId);
	 
	 int updateByPrimaryKeySe(CourseInfoEntity courseInfoEntity);
}