package com.jiacer.modules.mybatis.dao;

import java.util.List;
import java.util.Map;

import com.jiacer.modules.common.persistence.CrudDao;
import com.jiacer.modules.common.persistence.annotation.MyBatisDao;
import com.jiacer.modules.mybatis.entity.SchoolsEntity;
import com.jiacer.modules.mybatis.model.Schools;
import com.jiacer.modules.mybatis.model.SchoolsExample;
import org.apache.ibatis.annotations.Param;

@MyBatisDao
public interface SchoolsMapper extends CrudDao<SchoolsEntity>{

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table schools
	 * @mbggenerated  Thu Jun 22 11:46:28 CST 2017
	 */
	int countByExample(SchoolsExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table schools
	 * @mbggenerated  Thu Jun 22 11:46:28 CST 2017
	 */
	int deleteByExample(SchoolsExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table schools
	 * @mbggenerated  Thu Jun 22 11:46:28 CST 2017
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table schools
	 * @mbggenerated  Thu Jun 22 11:46:28 CST 2017
	 */
	int insert(Schools record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table schools
	 * @mbggenerated  Thu Jun 22 11:46:28 CST 2017
	 */
	int insertSelective(Schools record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table schools
	 * @mbggenerated  Thu Jun 22 11:46:28 CST 2017
	 */
	List<Schools> selectByExample(SchoolsExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table schools
	 * @mbggenerated  Thu Jun 22 11:46:28 CST 2017
	 */
	Schools selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table schools
	 * @mbggenerated  Thu Jun 22 11:46:28 CST 2017
	 */
	int updateByExampleSelective(@Param("record") Schools record, @Param("example") SchoolsExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table schools
	 * @mbggenerated  Thu Jun 22 11:46:28 CST 2017
	 */
	int updateByExample(@Param("record") Schools record, @Param("example") SchoolsExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table schools
	 * @mbggenerated  Thu Jun 22 11:46:28 CST 2017
	 */
	int updateByPrimaryKeySelective(Schools record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table schools
	 * @mbggenerated  Thu Jun 22 11:46:28 CST 2017
	 */
	int updateByPrimaryKey(Schools record);

	/**
	 * @param map
	 * @return
	 */
	Integer count(Map<Object, Object> map);

	/**
	 * @param map
	 * @return
	 */
	List<SchoolsEntity> getPageList(Map<Object, Object> map);
	
	
}