package com.jiacer.modules.mybatis.dao;

import com.jiacer.modules.common.persistence.CrudDao;
import com.jiacer.modules.common.persistence.annotation.MyBatisDao;
import com.jiacer.modules.mybatis.entity.TemplateInfoEntity;
import com.jiacer.modules.mybatis.model.TemplateInfo;
import com.jiacer.modules.mybatis.model.TemplateInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
@MyBatisDao
public interface TemplateInfoMapper extends CrudDao<TemplateInfoEntity> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table template_info
     *
     * @mbggenerated Wed May 24 17:50:47 CST 2017
     */
    int countByExample(TemplateInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table template_info
     *
     * @mbggenerated Wed May 24 17:50:47 CST 2017
     */
    int deleteByExample(TemplateInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table template_info
     *
     * @mbggenerated Wed May 24 17:50:47 CST 2017
     */
    int deleteByPrimaryKey(Integer templateId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table template_info
     *
     * @mbggenerated Wed May 24 17:50:47 CST 2017
     */
    int insert(TemplateInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table template_info
     *
     * @mbggenerated Wed May 24 17:50:47 CST 2017
     */
    int insertSelective(TemplateInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table template_info
     *
     * @mbggenerated Wed May 24 17:50:47 CST 2017
     */
    List<TemplateInfo> selectByExample(TemplateInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table template_info
     *
     * @mbggenerated Wed May 24 17:50:47 CST 2017
     */
    TemplateInfo selectByPrimaryKey(Integer templateId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table template_info
     *
     * @mbggenerated Wed May 24 17:50:47 CST 2017
     */
    int updateByExampleSelective(@Param("record") TemplateInfo record, @Param("example") TemplateInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table template_info
     *
     * @mbggenerated Wed May 24 17:50:47 CST 2017
     */
    int updateByExample(@Param("record") TemplateInfo record, @Param("example") TemplateInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table template_info
     *
     * @mbggenerated Wed May 24 17:50:47 CST 2017
     */
    int updateByPrimaryKeySelective(TemplateInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table template_info
     *
     * @mbggenerated Wed May 24 17:50:47 CST 2017
     */
    int updateByPrimaryKey(TemplateInfo record);
    
    
    //根据课程id查询判断题
    TemplateInfoEntity selectTfByCourseId(Integer courseId);
    //根据课程id查询单选题
    TemplateInfoEntity selectScByCourseId(Integer courseId);
    //根据课程查询多选题
    TemplateInfoEntity selectMcByCourseId(Integer courseId);
    
    int updateByPrimaryKeySe(TemplateInfoEntity templateInfoEntity);
}